name: game
description: A new Flutter project
version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.3.8
  provider: ^6.0.1
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.4.0
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
